export default function Deck() {
  const Deck = [
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
    { name: "Japan", temp: 0, weather: "rain", img: "" },
  ];
  return Deck;
}
