export default function Deck() {
  const Deck = [
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
    { name: "Japan", temp: 0, weather: "rain" },
  ];
  return Deck;
}
